[font]
size = 14.0

[font.normal]
family = "IosevkaTermSlab Nerd Font Mono"

[cursor]
style = { shape = "Underline", blinking = "On" }

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

