[font]
size = 12.0

[font.normal]
family = "Iosevka Nerd Font Mono"

[cursor]
style = { shape = "Underline", blinking = "On" }

[general]
import = [
    "~/.config/alacritty/themes/carbonfox.toml"
]

