[font]
size = 13.0

[font.normal]
# family = "IosevkaTermSlab Nerd Font Mono"
family = "FantasqueSansM Nerd Font Mono"

[cursor]
style = { shape = "Underline", blinking = "On" }

[general]
import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

